src/api/renderer.c, src/rencache.c, src/rencache.h, src/renderer.c, src/renwindow.c, src/renwindow.h
Moves the command buffer, buffer index and buffer size to the Windows struct.
In the future this will allow every Window to keep track of its own buffer, allowing multiple Windows to be created.
=> Attach command buffer to Renderer Window

data/plugins/language_js.lua
Added embedded html support as that used on React to JavaScript language plugin:
=> language_js: support for embedded html syntax

data/core/commands/findreplace.lua, data/core/doc/init.lua, data/core/doc/translate.lua, data/plugins/autocomplete.lua, data/plugins/language_css.lua
Added the ability of overwriting the default `config.symbol_pattern` and `config.non_word_chars` from language files by using the following properties:
* symbol_pattern
* non_word_chars
* symbol_non_word_chars - used by autocomplete plugin to detect the starting of a symbol when translating from current cursor position
This change will allow languages like css that support the `-` as part of a symbol name to define custom symbols pattern and non word characters for better autocompletion and lsp behavior.
Before and after demonstration with applied custom symbols pattern and non word chars to css language:
Before
https://github.com/pragtical/pragtical/assets/1702572/4ff9f8b8-ea7b-44b9-a4ef-9c4eafa3c6b0
After
https://github.com/pragtical/pragtical/assets/1702572/be9f710a-4397-42af-af59-a81e8 …
=> Syntax files symbol_pattern, non_word_chars props

data/plugins/linewrapping.lua
As described on issue #10 the linewrap plugin uses the docview width minus current scrollbar width to calculate the amount of text that can be visible. The scrollbar expand effect causes the wrapped text flow to change everytime the scrollbar is hovered. This commit fixes the issue by substracting from the docview width the full expanded size of the scrollbar.
=> Fixes #10 by using the scrollbar expanded size

data/core/contextmenu.lua
Fixes clicking on a contextmenu DIVIDER item which will try to execute the item command, not applicable in this case.
Shoulf fix #21
=> Do not process clicks on contextmenu divider

data/core/cli.lua, data/core/init.lua, data/core/start.lua
This is an ~~initial work in progress~~ implementation of the CLI parser that was discussed on https://github.com/pragtical/pragtical/issues/19#issuecomment-1702091348
Plugins should be able to register commands to provide additional CLI functionality using `cli.register(...)`.
The api in `core.cli`  is as follows:
```lua
---@alias core.cli.flag_type
---|>'"empty"'   # Does not needs a value
---| '"number"'  # A numerical value
---| '"string"'  # Any string value
---| '"boolean"' # 0,1,false,true
---| '"list"'    # Comma separated values
---Representation of a command line flag.
---@class core.cli.flag
---Long name of the flag eg: my-flag for --my-flag
---@field name string
---Short name eg: m for -m
---@field short_name string
---Description used for the flag when running `app help …
```
=> CLI parser API implementation

data/core/cli.lua, data/core/init.lua, src/main.c
These changes allow console output when running the editor from cmd on windows. The solution isn't perfect but this allow us not having to distribute a separate binary compiled in console mode just for the purpose of console output.
=> Fixes to allow console output on windows

resources/include/pragtical_plugin_api.h, src/api/api.h, src/api/system.c, src/compat/compat-5.3.c, src/compat/compat-5.3.h
Currently LuaJIT and PUC Lua 5.4 has some runtime differences that were not tackled by the pragtical_plugin_api.h which provides to native plugins the ability to run using the same Lua runtime that was linked to the editor.
This changes expose some buffer handling macros as functions for both LuaJIT and PUC Lua to resolve this issue. It also exports the LUA_REGISTRYINDEX macro as a "constant", since this value differs between LuaJIT and PUC Lua 5.4 causing segmentation faults and other related crashes.
The changes on this commit are an effort to support building ltreesitter (needed by Evergreen plugin) using the plugin_api mode, in order to support both LuaJIT and Lua 5.4 runtimes.
=> Better support the different supported runtimes

data/core/doc/highlighter.lua, data/core/doc/init.lua, data/plugins/drawwhitespace.lua, data/plugins/linewrapping.lua, docs/api/string.lua, docs/api/utf8extra.lua, src/api/utf8.c
=> Fix editor crash on invalid UTF-8

src/renderer.c
This prevent crashes when null checking to free non initialized elements that are not set to zero by malloc.
=> Use cmalloc instead of malloc on render init

data/core/commands/doc.lua, data/core/doc/init.lua
Some core functionality depends on checking current document subsyntax to determine proper syntax attributes. This isn't provided by evergreen which causes errors so we check if the state Is set before trying to iterate it.
=> Check tokenizer state to prevent issues with evergreen

data/core/init.lua
The issue was caused by the introduction of new project handling and the editor not doing a chdir to active project. Instead, we should rely on explicitly generating an absolute path using the current root project.
The issue was reported by @mundusnine
=> Fix project module sometimes not loading.

scripts/innosetup/innosetup.iss.in
This should prevent conflicting with lite xl installer as reported on discord channel.
=> Use unique guid for the inno setup installer

src/api/encoding.c
This change improves an issue reported (by Digger) on discord when opening huge files that causes the editor to stall.
This only improves the initial document encoding detection performance but could cause wrong detection if the MAX_READ_SIZE ends at a byte that breaks a utf-8 sequence, since we are naively setting a max size without verifying the utf8 codepoints directly from the file...
=> Limit max bytes read when detecting file encoding

data/core/init.lua, data/plugins/findfile.lua, data/plugins/projectsearch.lua, data/plugins/settings.lua
This PR adds various checks on editor components to respect config.file_size_limit and prevents opening huge files which aren't well supported by the editor yet. Changes include:
* Refresh treeview on settings gui file_size_limit change
* Respect file_size_limit on findfile plugin
* Respect file_size_limit on projectsearch plugin
* Respect file_size_limit on core.open_doc
This PR is related to #59
Edit: open file command still shows files that exceed the file_size_limit but I left that for navigation purposes since core.open_doc will now check the file_size_limit and prevent opening the file when it exceeds the limit
=> Respect config.file_size_limit on some components

data/core/docview.lua
This fixes an incorrect tab size when drawing lines that start with a custom font on the first symbol.
This issue was reported by @TorchedSammy on discord:
https://github.com/pragtical/pragtical/assets/1702572/a7fa87e4-055c-4b5f-ae94-e3ab60598367
How it looks now:
https://github.com/pragtical/pragtical/assets/1702572/6d9e6a95-9779-4686-90d5-61a1779474be
=> Fixes tab sizing when drawin lines

data/core/common.lua, data/plugins/autocomplete.lua
This change handles the issue reported on lite-xl/lite-xl-lsp#82 about the suggestions box becoming too wide to be visible when the symbols text is too large.
Instead of delegating the responsability to plugins making use of the autocomplete API we tackle the issue directly on the plugin itself by performing the required calculations to resize the suggestions box and truncate items text when needed.
https://github.com/pragtical/pragtical/assets/1702572/09e69438-c765-4d31-a9b0-8e7bc1756057
=> Added adaptive sizing to autocomplete plugin

data/core/start.lua
Previously, system.setenv was introduced without incrementing the mod version which would allow plugins to properly target this function. Also these other changes merit a modversion bump:
* get_partial_symbol() publicly exposed on autocomplete plugin which is been used by the LSP plugin
* renderer.font.get_metadata() now can be called as a method
=> Increase mod version from 3.3.1 to 3.4.0

subprojects/microtar.wrap, subprojects/packagefiles/microtar/meson.build, subprojects/packagefiles/ppm/meson.build
The plugin manager now ships a customized version of microtar as part of its source tree.
=> Removed no longer needed microtar subproject

src/api/system.c
This PR implements suggestions from mart-on-windows (#72) which are:
* Rename `ins` to `insert` which follows the same convention of the other keys matching already known names for easy keypad navigation.
* Name non-numlock key 5 from empty string to `clear` so it can be bind and use.
=> Implement non-numlock keycode suggestions from #72

subprojects/packagefiles/ppm/meson.build
This change is needed because msys doesn't ships mbedtls2. In order to easily fix the issue of pragtical failing to build with default meson flags under msys2 we just perform a whole static build of the plugin manager for this environment.
Fixes #74
=> Build the plugin manager statically for msys

data/plugins/autoreload.lua
Set config.plugins.autoreload.always_show_nagview to true as the default option to always ask the user before auto-reloading a file that has changed externally.
Fixes #81
=> Alert by default of changes in autoreload plugin

data/plugins/treeview.lua
This new config allows easily disabling the treeview toolbar at startup.
https://github.com/pragtical/pragtical/assets/1702572/bd27b5ca-a052-4f2e-a719-7ab7dcffd3b9
=> Add ui config to toggle the treeview toolbar

data/core/start.lua
This PR fixes the issue reported on issue [85](https://github.com/pragtical/pragtical/issues/85) within the editor, instead of relying on plugins adding the missing binaries PATH.
Fixes #85
=> Add /usr/local/bin to PATH on Mac OS X

data/core/keymap-macos.lua, data/core/keymap.lua
Assigns the binding `cmd+,`on Mac OS X and `ctrl+,` on all other operating systems as a quick way to open the Lua user module.
=> Assign a binding to open user module command

src/renderer.c
There is an assert that is triggered when the metrics of a font are bigger than the target surface to prevent buffer overwriting, since this only seems to happens in some exotic fonts we disable it until a proper fix is implemented.
This bug is caused by the merged PR lite-xl/lite-xl#1543
Fonts triggering the issue:
```
'/usr/share/fonts/noto/NotoSerifDivesAkuru-Regular.ttf' | X1: 6 -> W: 12, Y1: 12 -> H: 11
'/usr/share/fonts/noto/NotoSerifDivesAkuru-Regular.ttf' | X1: 5 -> W: 12, Y1: 12 -> H: 11
'/usr/share/fonts/noto/NotoSerifDivesAkuru-Regular.ttf' | X1: 5 -> W: 12, Y1: 12 -> H: 11
'/usr/share/fonts/noto/NotoSerifTest-Regular.ttf' | X1: 6 -> W: 12, Y1: 9 -> H: 8
'/usr/share/fonts/noto/NotoSerifTest-Regular.ttf' | X1: 5 -> W: 12, Y1: 9 -> H: 8 …
```
=> Disable assert on font resizing to allow fonts scanning.

data/core/init.lua, data/core/project.lua, data/core/start.lua, docs/api/system.lua, src/api/system.c
This change better supports plugins like the terminal without them having to implement current project path detection. When editing files not part of the root project the system will automatically chdir to their current parent directory.
Other changes include:
* added system.getcwd():string
* added core.current_project(filename?:string):core.project
* added Project:path_belongs_to(path):boolean
* increased the mod minor version as a result of newly introduced functions
=> Auto chdir to project depending on active document

data/core/common.lua
This removes the annoying missing fields warning when passing options to the common.serialize() function.
=> Mark common.serializeoptions fields as optional

data/core/config.lua, data/core/init.lua, data/plugins/settings.lua, data/plugins/workspace.lua
* The maximum amount of visited files is configurable with config.max_visited_files to prevent indefinite addition of visited files
* Visited files are cleared when opening a different project
* We now use the absolute path instead of relative to prevent issues with multiple project directories
* config.max_visited_files added to settings ui plugin
* save and restore core.visited_files on the workspace plugin for each project
=> Improvements to core.visited_files handling

data/core/statusview.lua
This change prepends the project name to the shown file path when more than one project is open, this allows easily identifying which project the file belongs to without having to display the full file path eg:
* Project 1: README.md -> pragtical/README.md
* Project 2: ~/Development/GitHub/scm/README.md -> scm/README.md
If only one project is open the previous behaviour is kept of only showing the filename or home encoded full path on foreign files.
Before:
After:
=> Multiproject handling for statusview doc:file

data/plugins/autoreload.lua
This prevent issues when the active view is rapidly changed.
=> Check doc is still in view before autoreloading it

data/core/encoding.lua, data/core/start.lua
For historical reasons iconv automatically replaces every \ with a Yen (¥) symbol when performing conversion from the Shift_JIS encoding. When opening source files this behaviour is undesired so we revert back every ¥ to a back slash.
Japanese fonts already provide the replacement for \ into a Yen.
Fixes #94
=> Handle conversion of \ to ¥ as reported on #94

data/core/doc/highlighter.lua, data/core/doc/init.lua, data/core/docview.lua, data/core/tokenizer.lua
Currently, DocView:get_col_x_offset() is an expensive operation when used on long lines. Plugins that use it extensively like: drawwhitespace, colorpreview or selectionhighlight, cause the editor to hang or not respond when dealing with huge lines.
Some example of files that cause the editor to hang are minified css or javascript files. While no one would casually edit these files it is totally normal to open them while inspecting a codebase.
For this reason a basic cache system is introduced caching the values returned by such functions when necessary. Another slow function can be DocView:get_x_offset_col(), so this change leverages the caching performed on col_x_offset to perform faster x_offset_col and keep it simple.
Beside adding the data cache, this work also introduces the ability …
=> Basic doc/docview cache for better performance

data/plugins/language_lua.lua
This change betters handle matching of placeholder chars, the given example now is better matched by the lua syntax plugin:
```lua
for _, _, value in some_iterator_that_returns_3() do
-- ...
end
```
=> Better matching of placeholder chars (_) on lua

data/core/init.lua
Changes include:
* Save the window size everytime the window mode changes except on fullscreen (we are interested on window size pre-fullscreen mode only for session restoration purposes).
* On startup delay setting window mode until the window is shown to prevent some issues. These issues include: - Windows OS making the window visible before rendering anything - On wayland not applying the window mode or size properly because the window was still hidden
* Introduced core.prev_window_mode to save the previous window mode when entering fullscreen mode, since we don't want to restore the fullscreen mode on startup.
=> Better restore of window mode/size on startup

data/core/encoding.lua
In some cases the encoding detection fails for UTF-16/32 files without a bom. For those cases we patched `encoding.detect` to perform a strict conversion test from the mentioned encodings and if it succeeds return it.
=> If encoding detect fails check if UTF-16/32 LE/BE

data/plugins/language_c.lua, data/plugins/language_cpp.lua
This allows matching symbols like #include or #ifndef so plugins like autocomplete can provide a list of the available keywords.
=> Added custom symbols to language c and cpp

data/plugins/autocomplete.lua
When triggered manually and first character is a punctuation, it causes none of the items to match if they don't also contain the punctiation. We remove the punctuations to ensure results with plugins like lsp will match even if the don't contain the starting punctuation symbol.
This solves issues in languages like C/C++ where # causes lsp to return a list of snippets as follows:
* if
* ifndef
* include
Without this change non of the items would match.
=> autocomplete: strip punctuations from partials

data/core/utf8string.lua, docs/api/utf8extra.lua
This also adds missing documentation for utf8extra equivalent utf8 compatibility functions.
=> Enable utf8 module for Lua < 5.3 using utf8extra

data/plugins/ipc.lua
This corrects the remanent of old function name to the new core.add_project().
=> Fix use of no longer valid core.add_project_directory

data/plugins/autocomplete.lua
Since core includes core.warn for some time know we substitute the direct call to `core.status_view:show_message`
=> Use core.warn on autocomplete plugin

data/core/init.lua, data/plugins/ipc.lua
This fix restores opening of a relative path from within the IPC plugin which was broken by #93
=> Fix for IPC plugin to open relative path

data/plugins/language_c.lua, data/plugins/language_cpp.lua
* Match enum names same as with structs and unions
* Match single line type declarations to better match code like:
```c
custome_type*
function_name (type *param_name)
{
/*...*/
}
```
* Added matching of single line param declaration without modifiers
* Allow spaces between function name and parameters list
* Also distinguish upper case constants when used as function calls
* Added matching of generic type declarations
Before and After preview:
=> Improvements to c/c++ language plugins

scripts/run-local
This change prevents issue with XDG_CONFIG_HOME overwriting the desired userdir since it has priority over HOME.
=> Use PRAGTICAL_USERDIR instead of HOME on run-local

data/core/cli.lua
The new flag `-f` or `--fork` can be used to launch the editor into a separate process when invoking it from a terminal. This returns control back to the terminal wich reverse implements #131 but still tackles the same issue.
Currently explicit `--fork` is easier to implement and requires less code than implicit forking and explicit `--wait`.
=> Add cli flag to allow forking editor to background

data/plugins/findfile.lua
Always use the current selection text value, if no selection was sent on submit and the text is not empty then open it as a new file.
Fixes issue reported on discord
=> Always select first result on findfile plugin

.gitmodules, scripts/run-local
This change removes the git submodule of widget which wasn't been kept up to date in favor of the meson subproject which has been working well and in the same vain of the colors and plugins meson subprojects.
Fixes confusion as in #147
=> Remove widget submodule in favor of subproject

meson.build, src/api/system.c
`system.get_scale()` always returned 1.0 (except the first time it was called which was a bug :D), since older macOS builds always had the renderer turned on and scaling was performed internally. That is not the case anymore and the software renderer needs to know current display scale when the displaychanged event is emitted.
This should fix the latest issue reported on #34 of UI elements getting too small when switching from:
retina -> external display -> back to retina
Basically system.get_scale properly returned 2.0 the first time the editor was started, then returned 1.0 when changing to external display and 1.0 when returning back to the retina display causing ui to get small.
=> Return actual scale on get_scale() for macOS too

data/plugins/scale.lua
Now `ctrl+shift+mousewheel[up|down]` or `ctrl+shift+[-|=|0]` can be used to only zoom the code of the editor. The scale mode was removed and scaling with `ctr+mousewheel` and friends will always change scale of entire interface.
**Preview:**
https://github.com/user-attachments/assets/49100d73-8142-4b14-8924-ab47f5e2dd6b
=> Scale plugin zoom code command and bindings

data/core/init.lua, data/plugins/scale.lua, docs/api/system.lua
Since new renwindow api (that allows initializing windows directly  Lua) the main window creation was moved to core.init but, the scale detection code was still been performed before. This meant that loading the default system style was using the incorrect scale causing issues that would only be resolved by manually re-scaling the interface.
Tried to wrongly fix the issue by delegating the responsibility to the scale plugin but that wasn't the correct solution (didn't notice what explained on first paragraph until later :sweat:). Now we defer style loading until main window is created and the default system scale properly detected, this ensures that the correct scale is set before performing any style calculations that rely on it.
Now besides updating scale on the displaychanged event it …
=> Adjust scale retrieveal on startup

data/core/logview.lua
This ensures that log items are properly sized each time the interface is rescaled.
=> When scale changes rescale item sizes on LogView

data/core/emptyview.lua
This checks if previously allocated icons font scale differs from current system scale at object instantiation to re-adjust the scale on situations like:
1. System scale is set to 200%
2. Open new editor window with EmptyView
3. Open another view (eg: document, settings ui)
4. Change the system scale to 100%
5. Close the active view returning to EmptyView with logo icon unscaled
=> Rescale the EmptyView icons font on instantiation

resources/windows/pragtical.exe.manifest.in
This change prevents the window getting automatically scaled by the operating system when user changes the system scale while the editor is open, which causes the interface to become blurry.
Some other changes include:
* Set the active code page to UTF-8 (win 10+)
* Enable more modern/efficient heap that reduces memory usage (win 10+)
References:
* https://learn.microsoft.com/en-us/windows/win32/sbscs/application-manifests
* https://learn.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process
=> Added PerMonitor dpi awareness to windows manifest

.github/workflows/release.yml, .github/workflows/rolling.yml
On the ubuntu builders meson doesn't automatically picks up ccache so we need to add its symlinks directory explicitly into the PATH.
We use ccache to speedup the AppImage generation which uses a non portable configuration and thus we recompile it from scratch instead of re-using already built binary and manually reconfiguring the install directories.
=> CI: Properly enable ccache for linux builds

resources/windows/pragtical.exe.manifest.in
Testing showed (thanks to @takase1121) that the new heap type introduced on windows 10 is not as great as been sold (at least for our use case). Performance can degrade for some operations and memory usage doesn't seems so different.
=> Revert utilization of newer heap type SegmentHeap

data/core/doc/highlighter.lua, data/core/doc/init.lua, data/core/init.lua, data/plugins/autocomplete.lua, data/plugins/autoreload.lua, data/plugins/detectindent.lua, data/plugins/drawwhitespace.lua, data/plugins/linewrapping.lua
Various core plugins that implement some caching rely on weak table keys of core.doc to cache content, with the idea that once the document is closed the cached content will be cleaned. The reality is that sometimes it can take a really long time until the garbage collector decides that the key is no longer been referenced and the cache data is kept longer than needed.
For this reason we now listen for Doc:on_close events and clean the cache immediately, applicable plugins are:
* autocomplete
* autoreload
* detectindent
* drawwhitespace
* linewrapping
These changes introduce a new `core.collect_garbage` flag that when set to true will queue a call to `collectgarbage('collect')`. Currently it is been employed each time a document is closed in an effort to reduce memory consumption.
We also …
=> Don't trust weak table keys to clean cached items

data/plugins/ipc.lua
On startup we chdir to the initial working directory to properly resolve the absolute path of given arguments. If no ipc method is called we just chdir back to currently loaded project.
=> IPC Plugin: restore current project working dir

data/plugins/findfile.lua
When a single project is open we were wrongly using the currently open file directory to calculate the absolute file path of selected results entry even if currently open file do not belongs to the project.
FindFile plugin goal is to open files related to currently open projects, for extraneous files there is core:open-file.
=> findfile: use project when resolving file path

src/api/regex.c
The value was been set to PCRE2_ANCHORED.
=> Fix regex api wrong value set to regex.ENDANCHORED

src/api/regex.c
Use uint32_t instead of int and luaL_optinteger instead of luaL_optnumber.
Possible fix for #166
=> regex api: use proper type for `options` parameter

data/core/init.lua
On macOS setting the size is enough, maximizing actually causes it to reset the window to normal status.
=> Do not maximize window on macOS at startup

data/core/config.lua, data/core/doc/highlighter.lua, data/core/init.lua, data/core/scrollbar.lua, data/core/tokenizer.lua, data/core/view.lua, data/plugins/settings.lua
* **set the maximum execution time of co-routines** - per frame iteration based on current frames per second.
* **penalizes co-routines that exceed the max_time** - by setting their waiting time to the same time it took to execute them.
* **Check how much co-routines to run per frame** - on each run_threads iteration we check how many can be run without exceeding the maximum time allowed.
* **Use the avg. runtime of co-routines to yield** - We now keep track of every 1 second cycle in order to see how much time is left for executing co-routine tasks, by using the average execution time of co-routines to decide if we should execute it or skip it until next 1 second cycle. 
* **introduce `core.fps`**  - has the maximum frames per second that are actually possible to render, which can be …
=> Lower input latency improving co-routine scheduling and tokenizer

data/core/emptyview.lua, data/plugins/detectindent.lua, data/plugins/settings.lua
The reduction is achieved by using a different strategy of initialization on some of the components shipped by default.
=> Reduce the amount of co-routines needed on startup

data/core/common.lua, data/core/init.lua, data/core/project.lua, data/plugins/findfile.lua, data/plugins/projectsearch.lua
Generalized Project class ignore file functions into new core functions that can be used by any plugin:
* core.get_ignore_file_rules()
* common.match_ignore_rule(path, info, ignore_rules)
Adapted findile and projectsearch plugins to use these functions that properly handle Windows path separators, pattern validation and rules.
Removed the original functions from Project class and replaced with generalized functions, also fixed some inconsistencies from the generalized Project functions and make use of relative file path when checking a file against Project:get_file_info().
=> Introduce new ignore files handling functions

data/core/titleview.lua
Processing the button actions on mouse pressed can cause conflicts with dragging so instead perform them on release which is also the way it should be.
=> Process TitleView button actions on mouse release

.github/workflows/release.yml, .github/workflows/rolling.yml
When building we need some dependencies to be present for proper configuration of SDL2 build. Ubuntu 20.04 didn't work when enabling the arm64 architecture so Ubuntu 22.04 was used instead. This means that aarch64 builds will require a newer linux distro to run.
May fix #179
=> Add aarch64 dependencies to CI

data/core/doc/init.lua, data/core/tokenizer.lua, docs/api/string.lua, docs/api/utf8extra.lua
These changes document the lax param used on some of the utf8extra functions which allows not checking if a string is valid utf8. Skipping this check gives a bit better performance so we use it on the tokenizer ulen() calls since we are always passing utf8 valid strings.
```lua
local value = string.rep("hoáélaéáásd", 10000, " ");
common.bench("ulen", function()
for i=1, 10000 do
value:ulen(nil, nil)
end
end)
common.bench("ulen lax", function()
for i=1, 10000 do
value:ulen(nil, nil, true)
end
end)
```
**Result:**
```
*** ulen             : 3160.357ms 18962.14%
*** ulen lax         :  795.085ms 4770.51%
```
=> Document lax param and use on tokenizer ulen calls

data/core/start.lua, meson.build
Since we are following a semver approach to versioning it is much easier to just use a single version number that represents both, the project version and the mods version.
Taken from https://semver.org/ and for reference:
1. MAJOR version when you make incompatible API changes
2. MINOR version when you add functionality in a backward compatible manner
3. PATCH version when you make backward compatible bug fixes
=> Use project version as mods version

data/core/doc/highlighter.lua
When doing the line state verification, check it is a valid before trying to access any of the state fields.
=> Check valid line state on retokenization check

data/plugins/language_js.lua
This change fixes the expressions used to match embedded html (as those used by reactjs) to prevent matching things that aren't html tags.
=> Fix language_js embedded html matching

data/core/config.lua, data/core/init.lua, data/plugins/settings.lua
Since the reduction in input latency is achieved by more rapidly processing background tasks when events are received, it can result on momentary higher cpu usage when moving mouse or typing.
This change introduces a toggle to disable this behavior if desired by user to reduce cpu usage.
=> Make the input latency reduction toggleable

src/main.c
Set the video driver backend to wayland by default if SDL_VIDEODRIVER not set and session type wayland.
Motivation from #189 to prevent unnecessary X11 issues when running on Wayland.
=> Use wayland by default if possible on linux

data/core/cli.lua
This change allows for subcommands to be able to specify if invalid arguments checking should not be performed. Useful for the wrapped cli access to the plugin manager thru `pragtical pm`, in order to allow things like `pragtical pm <...> --progress --assume-yes`.
=> CLI subcommands: allow skipping invalid arguments

data/core/dirwatch.lua
This change restores the unwatch/watch path behavior when receiving a change event which seemed to cause some issues on the past. It is needed on backends like inotify because when a file is deleted and re-added (like a git checkout <branch>) the watch is lost internally so we need to re-add it.
=> Restore DirWatch unwatch/watch behavior

data/plugins/autoreload.lua
The infinite watch loop occurs on backends like inotify where DirWatch:check will unwatch/watch the file on each check. If the change event is triggered twice in a row we get an infinite loop. Unwatching before save is required to prevent this issue.
This was the cause why unwatch/watch was previously disabled. Re-enabled on #193 because it is actually needed... Totally forgot why it was disabled in the first place and the doc explanation wasn't the real cause xD (and this explanation may not be either)
=> Autoreload: prevent infinite check loop on save

data/core/encoding.lua
Only perform backslash to placeholder replacement on non multi-byte sequences.
Should fix #201
=> Respect multi-byte sequences on SHIFT_JIS ¥ handling

src/api/encoding.c, src/api/system.c
Some headers that were implicitly included with SDL are now missing with sdl2-compat so we include them.
=> Explicitly added missing headers

src/main.c
Until this is fixed upstream we can't use the wayland video driver.
Reference: pragtical/pragtical#210
=> Do not use wayland on sdl2-compat v2.30.50+

data/core/commands/doc.lua, data/core/doc/init.lua, data/core/encoding.lua, data/core/statusview.lua, docs/api/encoding.lua, src/api/encoding.c
Main feature of these changes is that now we properly save the BOM if the loaded document originally contained one.
Other changes include:
* Updated encoding API functions to also return the BOM:
- encoding.detect
- encoding.detect_string
- encoding.strip_bom
* Return nil on `encoding.get_charset_bom()` if no applicable BOM.
* Updated encoding API Lua docs.
* Introduced `Doc:needs_encoding_conversion()` to simplify conversion logic.
* Introduced three new document bom handling commands:
- doc:disable-bom
- doc:enable-bom
- doc:toggle-bom
These changes should fix #214
=> Fix handling of documents Bytes Order Mark (BOM)

scripts/common.sh
Since pragtical can load binary files and handle various encodings and bytes order mark without crashing we are disabling the inclusion of the open_ext plugin on the github CI builds.
Thanks to Vinfall for the observation/suggestion!
=> Disabled addition of open_ext plugin on CI

src/api/shmem.c
Silence the compiler warnings around sprintf due to the repurposing of shmem_object name which in some cases can contain only an entry name, but in other a combination of namespace and entry name.
=> Silence shmem API compiler warnings

data/core/init.lua, data/plugins/settings.lua
This commit overrides the collectgarbage lua function to replace `collect` calls with a `step` to reduce system stuttering caused by miss use of this option. A forcecollect option was introduced in case it is explicitly needed to force a full garbage collection.
This change also adds a new Advanced pane settings with two new options to allow configuring the garbage collector pause and step multiplier values. Making these values less aggressive should result on better editor responsiveness with the downside of longer higher memory usage time spans.
=> Perform collectgarbage step instead of collect

src/api/system.c, src/main_com.c
This change should also fix a possible buffer overflow on main_com.c
Fixes #216, thanks to AmerM137 for reporting the issue.
=> Fix invalid size given to _wgetcwd

data/compat/module.lua
For some context:
We use https://github.com/lunarmodules/lua-compat-5.3 to add some of the newer Lua 5.3+ changes and recently we syncronized our copy with upstream on #224
The issue:
The compatibility code seems to have some workaround for the io module when patching LuaJIT that causes the file metatable type to be overwritten from `FILE*` to `userdata`, causing issues with native functions that expect a `FILE*`. On a quick inspection, this workaround does not seems to be required.
Fixes #228, thanks to AmerM137 for reporting the issue.
=> Disable a compatibility io overwrite on LuaJIT

src/api/system.c
While using compiz+xfce and the scale plugin, pragtical crashed after switching to another window. This crash was caused by sdl receiving+sending a mouse up event after the window lost focus, which caused the active window to not be found.
This change also moves from integers to floats for mouse coordinates for more precise positions with fractional scales.
=> Fix crash on out of window mouse events

src/api/regex.c
Forgot to subtract starting offset from subject length :D
=> Fix regex find_offsets not substracting offset

data/plugins/settings.lua
When changing the fonts path from the settings UI the raw DATADIR or USERDIR path is replaced with a placeholder to allow their path to be relocatable on portable installs as in the AppImage which creates a temporary directory.
=> Make DATADIR and USERDIR fonts path portable

meson.build, resources/README.md, resources/portable/README.md, scripts/innosetup/innosetup.sh
This makes portable builds truly portable since user settings will be stored on current pragtical location.
=> Include 'user' directory on portable installs

data/core/init.lua
Fixes plugin loading issue [evergreen-languages](https://github.com/Evergreen-lxl/evergreen-languages) plugins that have a mod-version header with a space in between.
=> Allow spaces in plugins mod-version

data/core/node.lua
This also fixes node resizing when a slibing node isn't visible.
=> Node: skip hidden tab events

src/renderer.c
Pragtical equivilant of https://github.com/lite-xl/lite-xl/pull/2098
During the migration from libagg to freetype2 the original code was adapted poorly and slight hinting is given the full weights which, depending on the font, may result in more noticable color fringes. 
For the built-in fonts there is no difference
=> restore light lcd filter for slight hinting

data/core/doc/init.lua
hard tabs are already aligned correctly thanks to https://github.com/lite-xl/lite-xl/pull/1945
before this PR soft tabs simply indented by the indent size instead of aligning to the indent size
=> align soft indention to indention size

data/core/config.lua, data/core/dirwatch.lua, docs/api/dirmonitor.lua, meson_options.txt, src/api/dirmonitor.c, src/api/dirmonitor/dirmonitor.h, src/api/dirmonitor/dummy.c, src/api/dirmonitor/fsevents.c, src/api/dirmonitor/inodewatcher.cpp, src/api/dirmonitor/inotify.c, src/api/dirmonitor/kqueue.c, src/api/dirmonitor/win32.c, src/meson.build
Pragtical version of https://github.com/lite-xl/lite-xl/pull/1949
also adds a config value to select the dirmonitor backend and graceful dirwatch error handling incase the user set a bad value.
=> rework dirmonitors to be able to support multiple backends

data/plugins/projectsearch.lua
Returns the focus to previous DocView when the project search is hidden. Should fix #272
=> projectsearch: on hide focus previous docview

data/core/common.lua
This is a continuation of #269 that returns the results on the expected table format while skipping sorting for files and sorting by names on non-files (which gives us a sorted commands palette).
=> Do not sort fuzzy results on empty needle

data/core/cli.lua
Display the available list of commands in alphabetical order.
=> cli: always display commands sorted by name

data/core/cli.lua, data/core/init.lua, data/plugins/ipc.lua
* New basic `repl` command useful to interactively execute Lua code with access to the Pragtical API. Supports single and multiple line expressions and includes some useful (maybe) built-in commands.
* New `run` command that allows executing Lua files or Lua code strings with access to the Pragtical API.
* Flags and commands list help output is now padded and wrapped.
* The current terminal columns width is detected for padding and wrapping.
* Now only treat as files the cli unhandled arguments.
* Support fetching value of single char flags when no spaces, eg: -Fvalue
* Support for insensitive true or false on boolean flags.
* Added new `edit` command to explicitly open a new editor instance by skipping the IPC system.
* Flags type and default value is now shown on help output. …
=> Add REPL and run commands to the CLI

subprojects/sdl2.wrap
For this we ship our own patched copy of the wrapdb meson files with fixes for wayland and whatever else we catch on CI,
=> Update SDL2 to latest fixes from master

data/plugins/language_lua.lua
Supports the form ffi.cdef [[ code ]]
=> language_lua: add c syntax coloring to ffi.cdef

data/core/config.lua, data/core/init.lua, data/plugins/settings.lua
Previously, a frame was drawn for every received event, causing the actual frame rate to exceed the configured cap (config.fps), especially under high event frequency.
Now, core.step() enforces the configured FPS limit more strictly, preventing unnecessary redraws and reducing CPU usage. This also improves the timing between frames, avoiding redundant draws when a frame was
just rendered.
Additionally, RootView:update was being triggered on every event, leading to excessive update calculations. Updates are now tied more closely to the frame rate rather than raw event frequency.
Finally, input latency should be reduced now by default without the previous cpu impact.
Expected result: reduced CPU usage and more consistent frame timing.
=> Limit FPS to match config.fps even during frequent events 

data/plugins/autocomplete.lua
Instead of returning an empty symbols list, at least return the symbols defined on the language definition of current file.
=> autocomplete: on max symbols return syntax_symbols

data/plugins/settings.lua
Going below 0.8 doesn't seems to be of any gain, you can always overwrite the permitted value by selecting the whole value and manually entering your desired one.
Should fix #298
=> settings ui: allow lowering line height to 0.8

src/api/system.c, src/renwindow.h
Since the hit test callback returns the mouse pointer in points we need to scale the given hit test information to prevent going beyond the correct boundaries.
Should fix #173
=> borderless: scale window hit test info

data/core/nagview.lua, data/core/node.lua
When having a lot of documents or views open, with a lot of plugins installed that perform actions on each update() call, the editor starts to become slow.
This change should fix that by:
* Performing View:update() only on active views.
* Drawing only the views that are truly visible as in the width and height been more than zero.
This also adapts NagView to properly work with this change.
=> Only update active views and draw visible ones

data/core/config.lua, data/core/docview.lua, data/plugins/settings.lua
As suggested by Amer, this adds a new config option that controls how much lines to keep visible above and below the cursor when performing certain scrolling operations (mainly cursor movement).
https://github.com/user-attachments/assets/1ae403a5-c260-49c8-9915-c846f546eb5d
=> Configurable amount of context lines visible on scroll

data/core/commands/doc.lua, data/core/commandview.lua
As suggested by Amer, this PR implement live syntax preview when typing text on the doc:go-to-line command. This is done by introducing a `draw_text` flag to the CommandView that accepts a function to perform custom text drawing.
https://github.com/user-attachments/assets/095801d2-3844-4f68-a882-fd3890558238
=> doc:go-to-line: live syntax preview

data/colors/default.lua, data/colors/fall.lua, data/colors/lite.lua, data/colors/summer.lua, data/colors/textadept.lua
This updates the pre-packaged color themes with the new `style.search_selection` and `style.search_selection_text` parameters.
@jgmdev feel free to modify my color selections. Also, I made the caret a little more visible in the `default` theme.
=> Add search highlight styles to pre-packaged themes

data/core/commands/core.lua, data/core/config.lua, data/core/docview.lua, data/plugins/settings.lua
Also adds a matching `core:toggle-line-numbers` command, and a graphical toggle on the settings interface,
=> Add built-in config to toggle line numbers

data/core/common.lua, data/core/emptyview.lua, data/plugins/settings.lua, data/plugins/treeview.lua
This functionality was fragmented thru the source code as in EmptyView, Settings and TreeView providing their own code to open links, files and directories using the system launcher.
Also various plugins on the plugins repo provide their own way. With this PR they can be adapted to use this function instead of duplicating the functionality.
Besides providing a built-in mechanism of opening resources with the operating system launcher, it also adds supports for other operating systems:
* Amiga
* Haiku
* SerenityOS
Also the function should provide a central location for supporting other systems if the need arises.
=> Add common.open_in_system(resource) function

data/core/commands/findreplace.lua, data/core/config.lua, data/plugins/settings.lua
As requested by Amer, this PR adds the ability to perform case insensitive next word selection on some find/replace commands.
New config flag:
```lua
---Perform case insensitive next word selection.
---
---The default is false.
---@type boolean
config.select_add_next_no_case = false
```
Applicable commands:
* find-replace:select-add-next
* find-replace:select-add-all
https://github.com/user-attachments/assets/12870d5c-105a-4e82-a3c1-6937a3b0fd8a
=> Add config option for insensitive next word selection

.github/workflows/pr_ci.yml, .github/workflows/release.yml, .github/workflows/rolling.yml, scripts/appimage.sh, scripts/build.sh, scripts/install-dependencies.sh, scripts/lua/README.md, scripts/lua/pgo.lua, scripts/run-local, src/meson.build
With the ability in pragtical of running external scripts with the `run` subcommand, this PR introduces a Lua script that can be used to generate profiler data for Profiler Guided Optimized builds.
1. To prepare the build for profile generation you need to pass -Db_pgo=generate to the setup flags, for example:
`meson setup --buildtype=release -Db_lto=true -Db_pgo=generate build`
2. Then you can install the files in order to be able to properly run the editor:
`meson install -C build --destdir ../install`
or simply use scripts/run-local to let it handle the installation for you
3. Run this script to generate the profiling data.
If using installed files: `install/pragtical run -n scripts/lua/pgo.lua`
If using run-local: `./scripts/run-local build run -n scripts/lua/pgo.lua`
If running on a …
=> Add PGO Stress Generator Script

scripts/lua/pgo.lua
This prevents CI builds from running for too long.
=> ci: allow max of 5 min on pgo stress

data/core/tokenizer.lua
When a child subsyntax was running from a parent subsyntax it was ended prematurely if an expression from parent subsyntax was found.
One example is the python syntax file that has a subsyntax for [] and {} pairs. If a string inside of these pairs contained a ] or } the string subsyntax was prematurely ended.
Example code:
```python
HEALTH_CHECK_GLOBS = [
"*/_health{/,}",
r"*/\[_health\]{/,}",
"*/live{/,}",
]
```
=> tokenizer: fix premature end of child subsyntaxes

data/plugins/language_python.lua
As reported by Amer the type declarations were incorrectly matching outside of the valid expression, this should fix:
```python
def somefunc(param1: int | None, param2: list[int], param3: tuple[int, string]):
'''some function that does something'''
var_name: 'int | string'
var_name: "int | string"
var_name: int | string
with open('file', 'r') as file:
content = file.read()
```
* Support forward declarations also on function params
* Match [rRuU] as function also on single quotes
Depends on #339
=> python: fix vars and params type hinting matching

data/core/init.lua
This change prevents adding a project that is already loaded.
=> Prevent duplicate projects on core.add_project
