pragtical/pragtical

data/core/init.lua
data/plugins/ipc.lua

This adds support for background threads (co-routines) without breaking current functionality. Also, if no background threads are registered the old behavior of waiting for events is maintained to keep cpu lower when unfocused. 
So far tested this functionality on the IPC and LSP plugins.

Added support for background threads

---

data/core/commands/root.lua
data/core/emptyview.lua
data/core/keymap.lua

Improved the EmptyView by converting it to a widget and adding widgets to it as shown below:

Converted emptyview to widget with additions

---

README.md

Add link, as bespoken: https://github.com/pragtical/pragtical/issues/6
Also slight rewording, taking out the slightly aggressive tone of 'seeing things as they are'
Guess this could solve the issue above.

Add link, slight rewording

---

data/core/doc/search.lua
data/plugins/projectsearch.lua
data/plugins/search_ui.lua

This PR finally adds support for project search and replace as mentioned on #1 using new SearchReplaceList widget from pragtical/widget#3

Add project wide search and replace support

---

src/api/thread.c

Also expose LUAJIT global var to threads.

Update thread initialization code to match main

---

data/plugins/treeview.lua

https://github.com/pragtical/pragtical/assets/1702572/d87928e3-263a-4032-923a-e7fbdaad064c

Enable horizontal scrollbar on treeview plugin

---

data/plugins/autocomplete.lua

This function will allow other plugins like LSP to easily access the partial symbol of the currently active DocView. Also this commit introduces:
* Documentation of internal data structures used by the plugin for easier understanding of the code and completion support.
* Documentation of the plublicly exposed functions.

Expose get_partial_symbol on autocomplete plugin

---

data/plugins/autocomplete.lua

This PR improves upon #67 and restores correct highlight colors.

Fixes to autocomplete re-sizing code

---

data/plugins/findfile.lua

Besides support for multiple projects this change also includes other improvements and new features like:
* introduction of cache that can be enabled to prevent useless regeneration of the files list (specially useful on huge projects)
* cache expiration time flag in minutes to control how often the files list should be regenrated
* status view button to manually refresh the files list
* better support for core.visited_files by marking the entries on the command view as "recent file"
* added related settings ui options to the plugin for the new configurable features
* fix handling of opening non-existant files
* select first entry on the files list if the user pressed enter with an empty input prompt, which allows easily switching between recent files

Support multiple projects on the findfile plugin

---

data/core/statusview.lua

This change prevents using unscaled fonts or styles that changed while the message was still being shown.

Render the statusview message on demand

---

data/core/node.lua

The issue was reported on lite-xl/lite-xl#1835

Support for utf-8 text reduction on node title

---

data/core/commands/core.lua
data/core/docview.lua
data/core/emptyview.lua
data/core/init.lua
data/core/nagview.lua
data/core/start.lua
data/plugins/autocomplete.lua
data/plugins/ipc.lua
docs/api/renderer.lua
docs/api/renwindow.lua
docs/api/system.lua
src/api/api.c
src/api/api.h
src/api/renderer.c
src/api/renwindow.c
src/api/system.c
src/main.c
src/meson.build
src/rencache.c
src/renderer.c
src/renderer.h

Rebases lite-xl/lite-xl#1751 with some additional related changes and fixes

Rebase window creation and management to Lua

---

meson.build
subprojects/colors.wrap
subprojects/pcre2.wrap
subprojects/plugins.wrap
subprojects/sdl2.wrap
subprojects/widget.wrap

Subprojects still to update for release:

Update subprojects for release

---

data/core/titleview.lua

Missed updating this on #108 to the updated system interfaces.

Updated titleview for lua windows updates

---

src/api/thread.c

Also added core.regex to start procedure of threads.

Fix thread initialization on non macOS bundle

---

data/core/emptyview.lua
data/core/view.lua
data/plugins/scale.lua
meson.build
src/api/system.c
src/renderer.c
src/renwindow.c
src/renwindow.h

Changes to restore better scale behaviour on SDL renderer (and even software renderer) which broke with previous code to improve font loading performance and font scaling.
Should improve situation reported on #34

Fix scaling logic regressions

---

data/plugins/search_ui.lua

This should make it in after new widget scale changes on pragtical/widget#9

Minor correction of replace button position

---

subprojects/widget.wrap

Hopefully removes another blocker for proper scaling...

Updated widgets to latest with smaller rescale fix

---

.github/workflows/release.yml
.github/workflows/rolling.yml
resources/cross/linux-aarch64.txt
scripts/appimage.sh
scripts/build.sh
scripts/package.sh

Adds Linux aarch64 support to the CI rolling and release builds as requested on #130

Add Linux AArch64 build target to CI

---

data/core/commands/core.lua
data/core/init.lua

* Properly gives core.window to set_window_size
* Properly table pack window dimensions for saving

Fix issues with window size restoration (spotted on Windows)

---

data/core/emptyview.lua
subprojects/widget.wrap

Also makes use of new Widget:schedule_update() on EmptyView.

Update widgets subproject to newest.

---

data/core/init.lua
data/plugins/scale.lua

* Keep DEFAULT_SCALE updated even if auto-detect is set to false.
* Adjustments to redundant default scale on scale plugin.

Always keep default scale updated on scale changes

---

data/plugins/autoreload.lua

Moves the path unwatch from the lua coroutine to Doc:on_close and removes redundant code.

Fully move autoreload cleanup from co to Doc:on_close

---

data/core/dirwatch.lua

This check properly tackles the infinite autoreload loop reported on #196 and fixes it directly on DirWatch to prevent similar issues from happening in other plugins. Still, the issue should be more properly inspected...

Fix DirWatch check duplication on multiple mode

---

data/core/cli.lua
src/main.c
src/main_com.c
src/meson.build

Adds a pragtical.com executable which is compiled in console mode and that calls into pragtical.exe to provide normal cli access when ran inside CMD or PowerShell.

Add a .exe to .com console wrapper on windows

---

src/api/system.c
src/main_com.c

Rebase of lite-xl/lite-xl#1864

api/system: make stat() call consistent across platforms

---

src/api/utf8.c

See: https://github.com/starwing/luautf8/pull/55 or https://github.com/starwing/luautf8/commit/1bb70d45208d4033dcc75efee968be70534dd3ab

Explicitly include limits.h on utf8 lib

---

data/plugins/treeview.lua

Properly suggest a path based on desired target.

Fix treeview new dir/folder path suggestions

---

src/main.c
src/main_com.c

This should allow standard input redirection from com wrapper into the actual pragtical.exe executable.

Also redirect stdin to console on windows

---

data/core/init.lua

* annotation.number
* annotation.keyword2
* annotation.literal

Added more annotation subtypes

---

scripts/common.sh
subprojects/packagefiles/ppm/build.sh

Seems like MSYS2 now reports cygwin as OSTYPE so we need to account for that.

Fix msys CI build

---

data/compat/file_mt.lua
data/compat/init.lua
data/compat/module.lua
data/core/bit.lua
data/core/start.lua
meson.build
src/api/api.c
src/api/api.h
src/compat/compat-5.3.c
src/compat/compat-5.3.h
src/compat/liolib.c
src/compat/lprefix.h
src/meson.build

* Updated lua-compat-5.3 to v0.14.4
* Lowered required PUC Lua from v5.4 to v5.2
* Enabled lua-compat-5.3 also on PUC Lua < 5.3

Sync lua-compat-5.3 with upstream

---

data/plugins/settings.lua

This change adds a filter textbox in the same way as with keybindings.

Settings: allow filtering colors

---

data/plugins/settings.lua
subprojects/widget.wrap

This change also updates the widget subproject to include the new word wrap functionality on labels.
https://github.com/user-attachments/assets/eafcec88-405e-466b-a7fb-9d836f6cc3a8

Enabled word wrap on settings ui labels

---

data/core/commands/core.lua
data/core/config.lua
data/core/node.lua
data/plugins/settings.lua

* Introduced config.hide_tabs set to false by default.
* Added core:toggle-tabs command.
* Added entry to settings UI.

Allow always hiding tabs, great for zen mode!

---

data/core/doc/search.lua

* Documented with doc comments for better autocompletion.
* Fixed rfind improper index calculations.
* Do not lower case text if Lua pattern.
* Keep original options on wrap.

Doc search fixes and types documentation.

---

data/plugins/search_ui.lua

This change allows using captured placeholders on the replacement text. The format for this placeholders are as follows:
* regular expressions: $[0-9]
* lua patterns: %[0-9]
This allows for some advanced in-place find and replace functionality on documents. For example:
* Lua pattern to search: (%a+)_(%a+)
* Replacement with capture placeholders: %2_%1
* Update results when the document is edited.
* Fix some endless loop when a Lua pattern doesn't match but still returns numerical indexes.
* Cleanup some compatibility code with regex match and find offsets.
* Don't replace text to find by current document selection if pattern or regex options are toggled on.

Capture replacements on regex/patterns search ui

---

data/core/doc/search.lua
data/plugins/search_ui.lua

* Better handle '.*' expressions.
* Correctly count all regex matches.
* Fixes to core.doc.search to properly handle whole line matches as the differences in offset values between Lua Patterns a Regex.

"Properly" handle whole line matches on doc search

---

subprojects/colors.wrap
subprojects/packagefiles/ppm/meson.build
subprojects/pcre2.wrap
subprojects/plugins.wrap
subprojects/widget.wrap

* Widgets for color picked sliders fix.
* Colors for new schemes.
* Plugins for new innoscript and pascal languages.
* pcre2 for new meson changes.
Also fixed forcefallback mode build of integrated ppm when building with the shell script.

Updated applicable subprojects.

---

data/core/init.lua

When a co-routine average time exceeded the maximum allowed running time we skipped it for the incorrect time instead of sleeping for its average time, this caused a delay in the re-execution of subsequent tasks.
This change also recalculates the co-routines re-execution wake time to account for the elpased time since the co-routine with the highest run priority was executed.

Wait thread avg time when it exceeds max time

---

data/plugins/search_ui.lua

This change hides the replace textbox and button on top and bottom modes to occupy less screen estate. It adds a replace toggle to enable the replace functionality. Also, it fixes the total results count getting reset after a replace.
https://github.com/user-attachments/assets/69aa1839-3079-4f2a-9b43-51fbf279badc

search_ui: hide replace by default, add toggle

---

data/core/config.lua
data/core/init.lua
data/plugins/settings.lua

* Frames per second
* Rendering speed measured in frames per second
* Maximum run time for a coroutine
* Amount of running coroutines

Add option to draw rendering stats

---

data/plugins/drawwhitespace.lua

This reverts commit f38723ea4698bf74b174625aba01731315123854.
DocView:get_col_x_offset was the major performance offender and now the returned offset value is internally cached. Another reason, caching a really long line causes more issues than what it solves.
Finally, we are now using DocView:get_visible_cols_range which should be a bit more faster than DocView:get_x_offset_col for resolving visible columns.

Revert "`drawwhitespace`: Cache whitespace location"

---

subprojects/luajit.wrap
subprojects/packagefiles/luajit/002-ARM64-Support-mcode-allocation-more-than-127MB-away-.patch
subprojects/packagefiles/luajit/002-arm64-mcode-allocation-fix.patch
subprojects/packagefiles/luajit/003-Support-placing-JIT-code-outside-of-jump-range-from-.patch

References:
https://github.com/LuaJIT/LuaJIT/issues/285
https://github.com/LuaJIT/LuaJIT/issues/285#issuecomment-1971854441 
https://github.com/corsix/LuaJIT/commits/arm64-jump-range/

luajit: arm64 patch to increase mcode alloc size

---

data/core/init.lua

Instead temporary lower maximum coroutines and their max run time.

Lower frame rate only after 3 consecutive drops

---

data/core/tokenizer.lua

This can increase tokenization performance up to 50% or 2x as shown on simple benchmark:
Inner functions       : 14.19575 sec (10000 iters)
Outer functions       : 7.27609 sec (10000 iters)
Edit: this is specially true for LuaJIT where it is able to better apply optimizations when tokenizer.tokenize is been deeply called. As an example, running the tokenizer with inner functions inside an `if else` condition will yield worst performance (as in the numbers above) than when run on the global scope.
Another benefit of moving the inner functions outside is a bit more of code clarity.

Move inner functions to outer on tokenizer.tokenize

---

data/plugins/settings.lua
subprojects/widget.wrap

Also adapted the settings ui colors and keybind lists to use the color references.

Updated widgets for color reference support

---

src/renderer.c

As reported by Amer and discussed on #323. The real cause was the code constantly trying to load the space character which is empty by default, this ended in a lot of calling into freetype api causing the performance issue.
Also, this PR caches the is_white_space check to reduce redundant calls to it and re-utilizes font metrics on font_load_glyph_bitmap().

Fixes performance regression by defer bitmap

---

data/plugins/projectsearch.lua

projectsearch: restore docview focus on hidden treeview

---

data/core/init.lua

As discussed with Amer this PR does the following to the window title:
* Show relative path of project files instead of absolute
* Show project only on file views
* Use previous path behaviour for non project files
* Make the function in charge of generating the title of view public to allow for modifications.
https://github.com/user-attachments/assets/b1dd6157-80ac-40e1-91b6-22801caa3a61

Change window title to include current project
